export const ADD_CHILD_PROFILE_SUCCESS = "[ADD PROFILE] ADD CHILD PROFILE SUCCESS";
export const ADD_CHILD_PROFILE_FAIL = "[ADD PROFILE] ADD CHILD PROFILE FAIL";
export const SIGN_IN_CHILD_SUCCESS = "[ADD PROFILE] SIGN IN CHILD SUCCESS";
export const SIGN_IN_CHILD_FAIL = "[ADD PROFILE] SIGN IN CHILD FAIL";
export const INVITE_BY_EMAIL_SUCCESS = "[ADD PROFILE] INVITE BY EMAIL SUCCESS";
export const INVITE_BY_EMAIL_FAIL = "[ADD PROFILE] INVITE BY EMAIL FAIL";
export const IS_DATA_FETCHING = "[ADD PROFILE] IS FETCHING";
export const CLEAR_STATE = "[ADD PROFILE] CLEAR STATE";
