export const GET_POPS_SUCCESS = "[ANALYTICs] GET POPS SUCCESS";
export const GET_POPS_FAIL = "[ANALYTICs] GET POPS FAIL";
export const GET_TOP_STATISTICS_SUCCESS = "[ANALYTICS] GET TOP STATISTICS SUCCESS";
export const GET_TOP_STATISTICS_FAIL = "[ANALYTICS] GET TOP STATISTICS FAIL";
export const CLEAN = "[ANALYTICS] CLEAN";
