export const GET_POPS_SUCCESS = "[ANALYTICs] GET POPS SUCCESS";
export const GET_POPS_FAIL = "[ANALYTICs] GET POPS FAIL";
export const GET_LINKTAPS_SUCCESS = "[ANALYTICS] GET LINKTAPS SUCCESS";
export const GET_LINKTAPS_FAIL = "[ANALYTICS] GET LINKTAPS FAIL";
