export const ADD_NEW_PROFILE_BY_EMAIL = "[EMAIL] ADD NEW PROFILE BY EMAIL";
export const ADD_NEW_PROFILE_BY_RANDOM_EMAIL = "[EMAIL] ADD NEW PROFILE BY RANDOM EMAIL";
export const INVITE_BY_EMAIL_SUCCESS = "[EMAIL] INVITE BY EMAIL SUCCESS";
export const INVITE_BY_EMAIL_FAIL = "[EMAIL] INVITE BY EMAIL FAIL";
export const REMOVE_FILE = "[EMAIL] REMOVE FILE";
export const IS_FETCHING = "[EMAIL] IS FETCHING";
export const CLEAR = "[EMAIL] CLEAR";
export const FILES_LIST = "[EMAIL] FILES LIST";
