import { makeStyles } from "@material-ui/core";

export default makeStyles((theme) => ({
  container: {
    padding: "100px 40px 50px 40px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  tempNameInputWrapper: {
    width: 300,
    padding: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  contentWrapper: {
    display: "flex",
    width: "100%",
    justifyContent: "center",
    paddingBottom: 20,
  },
  contentSideContainer: {
    width: "48%",
    maxWidth: 400,
    padding: 10,
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    "&:first-child": {
      marginRight: 50,
    },
  },
  itemWrapper: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
  },
  fieldTitle: {
    fontWeight: "bold !important",
    paddingBottom: 10,
  },
  addLinkButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#acacac",
    fontSize: "1rem",
    height: 30,
    width: "70%",
    border: "none",
    cursor: "pointer",
    borderRadius: 10,
    "& input": {
      display: "none",
    },
  },
  linksContainer: {
    display: "flex",
    flexDirection: "column",
    marginTop: 10,
    width: "100%",
    padding: "10px 0",
    maxWidth: "270px",
  },
  linkItemPadding: {
    padding: 5,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 65,
  },
  linksItemWrapper: {
    position: "relative",
    display: "flex",
    padding: 5,
    width: "90%",
    borderRadius: theme.custom.mainBorderRadius,
    boxShadow: theme.custom.mainBoxShadow,
  },
  iconItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    padding: 15,
    borderRadius: theme.custom.mainBorderRadius,
    boxShadow: theme.custom.iconBoxShadow,
    width: 40,
    height: 40,
  },
  closeIcon: {
    position: "absolute",
    top: "-10px",
    right: "-10px",
    color: "#808080",
    cursor: "pointer",
  },
  linkImage: {
    width: 30,
    height: 30,
  },
  textContainer: {
    display: "flex",
    flexDirection: "column",
    marginLeft: 20,
    width: "calc(100% - 70px)",
    "& > p": {
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
    },
  },
}));
