export const GET_COMPANY_INFO_SUCCESS = "[GENERAL SETTINGS] GET COMPANY INFO SUCCESS";
export const GET_COMPANY_INFO_FAIL = "[GENERAL SETTINGS] GET COMPANY INFO FAIL";
export const DELETE_PROFILE = "[GENERAL SETTINGS] DELETE PROFILE";
export const IS_DATA_FETCHING = "[GENERAL SETTINGS] IS DATA FETCHING";
export const CLEAR_STATE = "[GENERAL SETTINGS] CLEAR STATE";
export const IS_FILE_CONVERTING = "[GENERAL SETTINGS] IS FILE CONVERTING";
