export const GET_POPLS_SUCCESS = "[POPL] GET POPLS SUCCESS";
export const GET_POPLS_FAIL = "[POPL] GET POPLS FAIL";
export const ADD_POPLS_SUCCESS = "[POPL] ADD POPLS SUCCESS";
export const ADD_POPLS_FAIL = "[POPL] ADD POPLS FAIL";
export const EDIT_POPLS_SUCCESS = "[POPL] EDIT POPLS SUCCESS";
export const EDIT_POPLS_FAIL = "[POPL] EDIT POPLS FAIL";
