export const GET_POPLS_SUCCESS = "[POPL] GET POPLS SUCCESS";
export const GET_POPLS_FAIL = "[POPL] GET POPLS FAIL";
export const ADD_POPL_SUCCESS = "[POPL] ADD POPL SUCCESS";
export const ADD_POPL_FAIL = "[POPL] ADD POPL FAIL";
export const EDIT_POPL_SUCCESS = "[POPL] EDIT POPL SUCCESS";
export const EDIT_POPL_FAIL = "[POPL] EDIT POPL FAIL";
