export const ADD_NEW_PROFILE_BY_EMAIL = "[NEW PROFILE] ADD NEW PROFILE BY EMAIL";
export const ADD_NEW_PROFILE_BY_RANDOM_EMAIL = "[NEW PROFILE] ADD NEW PROFILE BY RANDOM EMAIL";

export const CLEAR = "[NEW PROFILE] CLEAR";
