export const ADD_NEW_PROFILE_BY_EMAIL = "[NEW PROFILE] ADD NEW PROFILE BY EMAIL";
export const ADD_NEW_PROFILE_BY_RANDOM_EMAIL = "[NEW PROFILE] ADD NEW PROFILE BY RANDOM EMAIL";
export const REMOVE_FILE = "[NEW PROFILE] REMOVE FILE";
export const CLEAR = "[NEW PROFILE] CLEAR";
export const FILES_LIST = "[NEW PROFILE] FILES LIST";
