export const SIGN_IN_SUCCESS = "[AUTH] SIGN IN SUCCESS";
export const SIGN_IN_FAIL = "[AUTH] SIGN IN FAIL";
export const SIGN_UP_SUCCESS = "[AUTH] SIGN UP SUCCESS";
export const SIGN_UP_FAIL = "[AUTH] SIGN UP FAIL";
export const LOGOUT = "[AUTH] LOGOUT";
export const GET_DASHBOARD_PLAN_SUCCESS = "[SYSTEM] GET DASHBOARD PLAN SUCCESS";
export const GET_DASHBOARD_PLAN_FAIL = "[SYSTEM] GET DASHBOARD PLAN FAIL";
export const CLEAN_STATE = "[AUTH] CLEAN STATE";
