export const selectConfig = [
  {
    id: 1,
    label: "Make Business",
    name: "makeBusiness",
    type: "button",
    checked: false,
  },
  {
    id: 2,
    label: "Make Personal",
    name: "makePersonal",
    type: "button",
    checked: false,
  },
  {
    id: 3,
    label: "Turn direct on",
    name: "makeDirectOn",
    type: "button",
    checked: false,
  },
  {
    id: 4,
    label: "Turn direct off",
    name: "makeDirectOff",
    type: "button",
    checked: false,
  },
  {
    id: 5,
    label: "Turn Profile on",
    name: "turnProfileOn",
    type: "button",
    checked: false,
  },
  {
    id: 6,
    label: "Turn Profile off",
    name: "turnProfileOff",
    type: "button",
    checked: false,
  },
  {
    id: 7,
    label: "Add link",
    name: "addLink",
    type: "button",
    checked: false,
  },
];
