export const GET_CONNECTIONS_SUCCESS = "[CONNECTIONS] GET CONNECTIONS SUCCESS";
export const GET_CONNECTIONS_FAIL = "[CONNECTIONS] GET CONNECTIONS FAIL";
export const ADD_CONNECTIONS_SUCCESS = "[CONNECTIONS] ADD CONNECTIONS SUCCESS";
export const ADD_CONNECTIONS_FAIL = "[CONNECTIONS] ADD CONNECTIONS FAIL";
export const EDIT_CONNECTIONS_SUCCESS = "[CONNECTIONS] EDIT CONNECTIONS SUCCESS";
export const EDIT_CONNECTIONS_FAIL = "[CONNECTIONS] EDIT CONNECTIONS FAIL";
export const CLEAR_ADD_CONNECTIONS = "[CONNECTIONS] CLEAR ADD CONNECTIONS";
export const CLEAR_EDIT_CONNECTIONS = "[CONNECTIONS] CLEAR EDIT CONNECTIONS";
