export const PROFILE_DATA = "[SYSTEM] PROFILE DATA";
export const ALERT = "[SYSTEM] ALERT";
export const PROFILE_INFO_FOR_SIDE_BAR = "[SYSTEM] PROFILE INFO FOR SIDE BAR";
export const PROFILE_COUNT_TIER_LEVEL = "[SYSTEM] PROFILE COUNT TIER LEVEL";
export const SUBSCRIPTION_INFO = "[SYSTEM] SUBSCRIPTION INFO";
export const FETCHING_ACTION = "[SYSTEM] FETCHING ACTION";
export const UPDATE_CONNECTIONS = "[SYSTEM] UPDATE CONNECTIONS";
export const SHOW_RESTRICTED_MODE = "[SYSTEM] SHOW RESTRICTED MODE";
