export const ADD_NEW_PROFILE_BY_EMAIL = "[NEW ACCOUNT] ADD NEW PROFILE BY EMAIL";
export const ADD_NEW_PROFILE_BY_RANDOM_EMAIL = "[NEW ACCOUNT] ADD NEW PROFILE BY RANDOM EMAIL";
export const REMOVE_FILE = "[NEW ACCOUNT] REMOVE FILE";
export const IS_FETCHING = "[NEW ACCOUNT] IS FETCHING";
export const CLEAR = "[NEW ACCOUNT] CLEAR";
export const FILES_LIST = "[NEW ACCOUNT] FILES LIST";
