export const GET_DATA_PROFILES_SUCCESS = "[PROFILE] GET DATA PROFILES SUCCESS";
export const GET_DATA_PROFILES_FAIL = "[PROFILE] GET DATA PROFILES FAIL";
export const GET_PROFILES_IDS_SUCCESS = "[PROFILE] GET PROFILES IDS SUCCESS";
export const GET_PROFILES_IDS_FAIL = "[PROFILE] GET PROFILES IDS FAIL";
export const ADD_LINK_SUCCESS = "[PROFILE] ADD LINK SUCCESS";
export const ADD_LINK_FAIL = "[PROFILE] ADD LINK FAIL";
export const ADD_CHILD_PROFILE = "[PROFILE] ADD CHILD PROFILE";
export const CLEAR_STATE = "[PROFILE] CLEAR STATE";
