export const GET_PROFILES_SUCCESS = "[POPL] GET PROFILES SUCCESS";
export const GET_PROFILES_FAIL = "[POPL] GET PROFILES FAIL";
export const ADD_PROFILES_SUCCESS = "[POPL] ADD PROFILES SUCCESS";
export const ADD_PROFILES_FAIL = "[POPL] ADD PROFILES FAIL";
export const EDIT_PROFILES_SUCCESS = "[POPL] EDIT PROFILES SUCCESS";
export const EDIT_PROFILES_FAIL = "[POPL] EDIT PROFILES FAIL";
